Autor
faateodoro/cdc-java pull request #1
Opened 2021-04-28 21:33 UTC by faateodoro

Código feito com validações feitas diretamente no construtor (Não sei se é uma boa prática ou não).

Controller entrega todos autores. No cadastro retorna 201 ou 400.

2021-05-03 22:03 UTC, alexandreaquiles requested changes

2021-05-03 22:03 UTC, alexandreaquiles commented on src/main/java/br/com/faateodoro/nossacasadocodigo/controller/dto/AutorForm.java
> +public class AutorForm {
Como é uma API, temos o costume de chamar de `AutorRequest` ou `AutorInput`.

Também é comum ligarmos com a criação de um novo autor. Aí, ficaria algo como `NovoAutorRequest`.

2021-05-03 22:03 UTC, alexandreaquiles commented on src/main/java/br/com/faateodoro/nossacasadocodigo/controller/dto/AutorForm.java
> +    private String descricao;
Seria interessante já fazer as validações o quanto antes, nesse objeto que recebe as informações do request.

Vale usar anotações como `@NotBlank`, `@Size` e outras do Bean Validation.

2021-05-03 22:03 UTC, alexandreaquiles commented on src/main/java/br/com/faateodoro/nossacasadocodigo/modelo/Autor.java
> +            throw new IllegalArgumentException("Nome não pode ser nulo ou vazio.");
Seria interessante usar validações com o Bean Validation (`@NotBlank`, `@Size`).

2021-05-03 22:03 UTC, alexandreaquiles commented on src/main/java/br/com/faateodoro/nossacasadocodigo/modelo/Autor.java
> +                .find();
O Bean Validation tem a anotação `@Email`, que facilita muita coisa.

2021-05-06 22:29 UTC, alexandreaquiles commented on src/main/java/br/com/faateodoro/nossacasadocodigo/controller/AutorController.java
> +    @Autowired
Aqui nem precisa do `@Autowired`!

```suggestion
 
```

2021-05-06 22:33 UTC, alexandreaquiles commented on src/main/java/br/com/faateodoro/nossacasadocodigo/controller/dto/AutorRequest.java
> +    @NotBlank(message = "O nome é obrigatório")
Fabiano, eu prefiro que você use internacionalização.

É uma boa prática separar as mensagens do código.

Aí, ficaria assim:

```suggestion
    @NotBlank(message = "{autor.nome.obrigatorio}")
```

E no `ValidationMessages.properties` em `src/main/resources`, você coloca a mensagem:

```properties
autor.nome.obrigatorio = O nome é obrigatório
```

2021-05-06 22:45 UTC, alexandreaquiles commented on src/main/java/br/com/faateodoro/nossacasadocodigo/controller/dto/AutorRequest.java
> +    }
Não precisa desses getters.

2021-05-06 22:46 UTC, alexandreaquiles commented on src/main/java/br/com/faateodoro/nossacasadocodigo/controller/dto/AutorRequest.java
> +    @Size(max = 400, message = "Adescrição nãopode conter mais que 400 caracteres")
Espaços na mensagem.

```suggestion
    @Size(max = 400, message = "A descrição não pode conter mais que 400 caracteres")
```

2021-05-06 22:47 UTC, alexandreaquiles commented on src/main/java/br/com/faateodoro/nossacasadocodigo/modelo/Autor.java
> +    public Autor(){}
Colocar `@Deprecated` aqui. Pode deixar esse construtor padrão como `private`.

2021-05-06 22:49 UTC, alexandreaquiles commented on src/main/java/br/com/faateodoro/nossacasadocodigo/modelo/Autor.java
> +    public Long getId(){
Só pra deixar claro, esses getters são necessários porque são usados na hora de montar o JSON de resposta.

2021-05-06 22:53 UTC, alexandreaquiles commented on src/main/java/br/com/faateodoro/nossacasadocodigo/modelo/Autor.java
> +        this.nome = nome;
A gente gosta de usar asserts para garantir que o objeto é construído num estado inválido. Não dá pra fazer isso no `Request`, porque ele vem de fora. Mas esse objeto é construído a partir do request e deveria estar num estado perfeito. Se não tiver, é BUG!

Poderia fazer algo como:

```java
Assert.hasLength(descricao, "deveria ter texto");
Assert.isTrue(descricao.length() <= 400, "não pode passar do máximo de caracteres");
```

Mais detalhes: https://www.baeldung.com/spring-assert

2021-05-06 22:54 UTC, alexandreaquiles commented on src/main/java/br/com/faateodoro/nossacasadocodigo/validacao/ErrorHandling.java
> +@RestControllerAdvice
Perfeito! :+1:

2021-05-06 22:54 UTC, alexandreaquiles commented on src/main/java/br/com/faateodoro/nossacasadocodigo/validacao/ValidacaoErroResponse.java
> +public class ValidacaoErroResponse {
Perfeito! :+1:

2021-05-06 22:58 UTC, alexandreaquiles requested changes

2021-05-06 22:58 UTC, alexandreaquiles commented on src/main/java/br/com/faateodoro/nossacasadocodigo/controller/AutorController.java
> +    @GetMapping("/autor")
Sobre as URLs do Controller, é costume usar no plural.

O importante mesmo é ser consistente, e você foi.

Mas eu prefereria que você fizesse:

- `GET /autores`: lista todos os autores
- `POST /autores`: adiciona um novo autor

A ideia é discutida em um post sobre [Boas práticas REST](https://blog.caelum.com.br/rest-principios-e-boas-praticas/amp/) no blog da Caelum.

Método | URI | Utilização
-- | -- | --
GET | /clientes | Recuperar os dados de todos os clientes.
GET | /clientes/id | Recuperar os dados de um determinado cliente.
POST | /clientes | Criar um novo cliente.
PUT | /clientes/id | Atualizar os dados de um determinado cliente.
DELETE | /clientes/id | Excluir um determinado cliente.

2021-05-07 12:59 UTC, faateodoro commented on src/main/java/br/com/faateodoro/nossacasadocodigo/controller/dto/AutorRequest.java
> +    @Size(max = 400, message = "Adescrição nãopode conter mais que 400 caracteres")
esse meu teclado tem dificuldades com o espaço =/

2021-05-07 14:34 UTC, faateodoro commented on src/main/java/br/com/faateodoro/nossacasadocodigo/controller/AutorController.java
> +    @Autowired
Opa, bom saber disso!

2021-05-07 16:38 UTC, alexandreaquiles requested changes

2021-05-07 16:38 UTC, alexandreaquiles commented on src/main/java/br/com/faateodoro/nossacasadocodigo/controller/AutorController.java
> +@Validated
Fabiano, acho que não precisa desse `@Validated` também. Apenas o `@Valid` no método já basta.

```suggestion
```

2021-05-07 16:38 UTC, alexandreaquiles commented on src/main/java/br/com/faateodoro/nossacasadocodigo/controller/AutorController.java
> +    public ResponseEntity cadastrar(@RequestBody @Valid AutorRequest autorRequest,
Seria interessante colocar o tipo do retorno no `ResponseEntity`.

```suggestion
    public ResponseEntity<Autor> cadastrar(@RequestBody @Valid AutorRequest autorRequest,
```

2021-05-07 16:38 UTC, alexandreaquiles commented on src/main/java/br/com/faateodoro/nossacasadocodigo/controller/dto/AutorRequest.java
> +        Assert.isTrue(descricao.length() <= 400, "A descrição não pode conter mais que 400 caracteres");
Não precisa do assert nos objetos de borda, apenas nas entidades.

2021-05-07 16:38 UTC, alexandreaquiles commented on src/main/java/br/com/faateodoro/nossacasadocodigo/controller/dto/AutorRequest.java
> +    }
Não precisa validar nos objetos de borda.

2021-05-07 16:38 UTC, alexandreaquiles commented on src/main/java/br/com/faateodoro/nossacasadocodigo/modelo/Autor.java
> +        this.nome = nome;
A ideia seria fazer a programação defensiva por aqui.

Como disse no Slack:

> Aqui o Otavio Lemos explica o conceito, de maneira mais ampla
> https://www.youtube.com/watch?v=INslrb0KM1g
> a ideia desses Asserts seria verificar pré-condições para a chamada do construtor
> mas não faz sentido fazer isso em objetos "de borda" como o Request
> esses objetos vem de fora e aceitam qualquer coisa
> mas a gente já colocou validações nele, né?
> então não deveria passar nenhum erro de validação para a entidade
> se tem algo nulo, em branco, por exemplo, é bug em algum lugar do código
> o princípio aqui é que podemos checar as pré-condições para criar um objeto
> esses Asserts não tem a ver com testes, mas com ser defensivo, assegurar que algo não será nulo

2021-05-07 16:38 UTC, alexandreaquiles commented on src/main/resources/ValidationMessages.properties
> +autor.descricao.obrigatório = "A descrição é obrigatória"
As mensagens não precisam de aspas aqui, porque senão vão aparecer lá no response.

Ficaria assim:

```json
[
  {
    "campo": "email",
    "mensagem": "\"O email é obrigatório e deve ter o formato válido\""
  }
]
```

2021-05-07 22:26 UTC, alexandreaquiles approved these changes
Boa, Fabiano! Acho que é isso!

2021-05-08 14:16 UTC, merged